filebeat.prospectors:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log
- paths:
    - /usr/share/filebeat/logs/marketing/*.log
  document_type: marketing

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: kibana
  username: elastic
  password: youpassword

output.elasticsearch:
  hosts: elasticsearch
  username: elastic
  password: youpassword
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
